### ISSUE TITLE
Replace Martini with idiomatic HTTP middleware

### ISSUE THREAD

**Issue by vegax87** [9uuso/vertigo#27]
Negroni is a HTTP library written by the same authors of Martini framework and it's not heavy like Martini, performance benchmarks show Negroni can handle many more requests/sec than Martini and has a good support of 3rd party middlewares

Repo: https://github.com/codegangsta/negroni

Benchmarks: https://github.com/hgfischer/martini-vs-negroni

**Comment by jayrox** [comment]
i'd be willing to entertain the idea of switching

**Comment by 9uuso** [comment]
I have been thinking about switching over eventually, as I believe that using Gos native HTTP handlers (which Negroni uses) will be both easier to maintain and develop.

That being said, switching over would probably be one day job, but because the two benefits of Negroni (speed, code simplicity) do not add any actual features, the issue has not been very high on my list. Plus, I do not have much spare time at the moment, so I am unlikely to code it up myself. 

Though I am open to any PRs you might make. :)

**Comment by 9uuso** [comment]
I've started to switch away from Martini now, but I'm afraid negroni won't be used. I've done a lot of research during the past days and [a blog post from Justinas Stankevičius](https://justinas.org/alice-painless-middleware-chaining-for-go/) mentioned the following:
```
Flaws of other approaches

Many might point out that there are existing solutions for chaining middleware. That's true, but any of the solutions I had looked into had at least one thing that I thought should be done in a differently.

The recent Negroni package allows handlers to be added as middleware like this:

n := negroni.Classic()
// func (n *Negroni) UseHandler(handler http.Handler)
n.UseHandler(myMiddleware)

See the fault here? Traditional net/http middleware wrap the next handler so the wrapper can have a total control. Here, there's simply no handler to pass in. You can't pass in the Negroni instance as it would result in infinite recursion (Negroni calls middleware calls Negroni).

Negroni has its own mechanism for control flow (next() to call the following handlers), but you have to modify your middleware to fully utilize it, which is not ideal.
```

For now, I'm using [alice](https://github.com/justinas/alice) in my uncommitted development branch, but whether I'll stick with it is yet undecided.

Migrating away from Martini is actually quite enormous task, as it requires me to migrate away from all contribution libraries as well, which are:

* github.com/martini-contrib/binding
* github.com/martini-contrib/render
* github.com/martini-contrib/sessions
* github.com/martini-contrib/strict

I'm most likely required to use an alternative package for `binding` and `sessions`, from which the Gorilla toolkit seems like a good choice. The strict package is will be most likely stripped off and replaced by `http.Handler` compliant middleware. Render library will most likely also get scrapped and replaced by Go's standard library to resolve a few raised issues like #32 and switch statements in the end of each route.

I'm unable to tell how fast these changes will be made, since the time I'm able to dedicate varies a lot. There also might be a good number of issues with replacing each of the components. However, once these changes are made, I'm pretty confident in freezing the API and the application structure. Although, I'm still yet to talk with the author of [Hugo](https://github.com/spf13/hugo) about the API structure, as he showed interest in unifying Hugo's and Vertigo's API together. If it ever becomes a thing, I'm sure to open a new ticket, but for now the best way to watch the changes is by looking at the `[dev](https://github.com/9uuso/vertigo/tree/dev)` branch. Recent, notable changes include the new `mail` package, which trades forced Mailgun integration with standard library SMTP package and the removal of HTML editing support. Removal of Atom or RSS is also underway, but for now I can't decide which one to throw to the trash bin.

**Comment by jayrox** [comment]
Glad to see you are using Alice as your middleware because that is what I used on my uncommitted branch. I will work on getting it it to github today. Its fully functional as far as I can tell just some tests that fail. The tests fail mostly due to sessions, something I am not strong with unfortunately. 

I've created a strict type set of functions that seem to work well with the current needs, of course they can be adjusted to the greater needs.

Between Atom and RSS, I would suggest keeping RSS as it appears to me the more common used api.

My branch using Alice does not have the full feature set and helpers that my fork using martini has, mostly because I wanted your's to be the base in which we build from.

**Comment by jayrox** [comment]
got the code committed https://github.com/jayrox/Vertigo-alice

**Comment by 9uuso** [comment]
Thanks! This will sure come handy.

**Comment by jayrox** [comment]
No problem, hope it helps. Please feel free to ask any questions if you
aren't sure of the way something works or a decision I made an why.

**Comment by JanSichula** [comment]
@9uuso +1 for "Replace Martini with idiomatic HTTP middleware".

Nevertheless thank you for this great project which we will possibly use for our new church web site.

**Comment by 9uuso** [comment]
I started working on this issue this week and I hope to be able to close this ticket by February. I ended up choosing alice for middleware chaining and gorilla mux as the multiplexer. So pretty much the same packages what @jayrox had 6 months ago.

There will also be major changes on the routing. I will be implementing gorilla/context for passing on sessions and form data. This will be part of a change to migrate settings to be part of the SQL package, which will require some voodoo to get right. Abstracting the settings package to be part of the database driver results in import cycles currently. Adding HTTP contexts should let me avoid those issues.

The reason for rewriting settings package is to make Vertigo deployable in Google App Engine.

**Comment by jayrox** [comment]
That's good news, is any of the code I supplied usable for this?

**Comment by 9uuso** [comment]
Most of it. However, because I made changes after that, I can't automatically migrate changes.

Your code does give a good source to compare the changes, but unfortunately there is a lot to be rewritten.

**Comment by jayrox** [comment]
gotcha, if there is anything i can help with let me know.

**Comment by 9uuso** [comment]
I am unable to get certain API routes registered by the router. I am currently using multiplexer called [vestigo](https://github.com/husobee/vestigo), but gorilla/mux did not seem to work either. The failing route is [/api/post/:slug/edit](https://github.com/9uuso/vertigo/blob/master/main.go#L113). I will see if I find the time to push the code into its own branch later this weekend.

Besides of that one route, there does not seem to be much more to fix for full test coverage. I estimate the rest of the bugs to take only a few hours to fix.

**Comment by jayrox** [comment]
i'll have a look at it when you push the code

**Comment by 9uuso** [comment]
The problem was (in a way) in the router. I opened an issue about it in [here](https://github.com/husobee/vestigo/issues/8). If nothing can be done, then I will just change the URL structure for new posts and search.

On another note, the tests currently pass for everything else. I also have the database methods for settings written. The latter will be a breaking chance, but it will push the project towards being a single binary blog engine even more.

**Comment by 9uuso** [comment]
The tests are currently passing on /dev, where you can see the big changes. I will be polishing the code a bit before merging, which should happen sometime next week.
