### ISSUE TITLE
source installation errors

### ISSUE THREAD

**Issue by netbun** [9uuso/vertigo#44]
errors seem the begin around `cd vertigo && godep get ./ && godep go build`

**Comment by 9uuso** [comment]
Thanks for pointing this out! It looks like godep is unable to fetch the local dependencies, such as `vertigo/database/gorm` or `vertigo/settings`, which cause the errors with `godep get`.

Because the required packages are vendored in `Godeps` folder, the `godep get` command is actually unnecessary. I've removed all uses of it now. Builds should be slightly faster if you use Docker.

**Comment by netbun** [comment]
@9uuso :+1:
